#!/bin/bash

set -e

full_version=$(php-config --version | egrep '[0-9]\.[0-9]\.[0-9]{1,2}' | cut -d'-' -f1)
major=$(echo ${full_version} | cut -d. -f1)
minor=$(echo ${full_version} | cut -d. -f2)
patch=$(echo ${full_version} | cut -d. -f3)
php_version="${major}.${minor}"

sysconfdir=/etc/php/${php_version}
extension_dir=$(php-config --extension-dir)

cli_confdir=${sysconfdir}
cli_ini=php-cli.ini

sapi_confdir=${sysconfdir}
pool_conf=${sapi_confdir}/fpm/pool.d/www.conf

APP_ENV=${APP_ENV:-"debug"}
if [[ "${APP_ENV}" =~ ^dev* ]]; then
    APP_ENV="dev"
fi
if [[ "${APP_ENV}" =~ ^prod* ]]; then
    APP_ENV="prod"
fi

xdebug_default_port=9000

ENABLE_FPM_SOCKET=${ENABLE_FPM_SOCKET:-"on"}

if [ "${APP_ENV}" != "prod" ] && [ "${APP_ENV}" != "debug" ] && [ "${APP_ENV}" != "dev" ];then
    APP_ENV="debug"
fi

if [ ! -d ${sapi_confdir} ] || [ ! -d ${cli_confdir} ];then
    echo "Diretórios de configurações PHP inexistentes! \n"
    exit 1 
fi
if [ ! -f ${sapi_confdir}/fpm/php.ini ] || [ ! -f ${cli_confdir}/${cli_ini} ];then
    echo "Arquivos de configurações PHP inexistentes! \n"
    exit 1 
fi

# Atualiza configuração. Descomenta se estiver comentada
update_config() {
    file="${1}"
    conf_list="${2}"
    if [ -f "${file}" ] && [ -n "${conf_list}" ]; then
        confs=($(echo ${conf_list}))
        for conf in "${confs[@]}"; do
            param=$(echo ${conf} | sed -E -n -e 's/^([0-9\.a-z\_]+)\=.*/\1/p')
            valor=$(echo ${conf} | sed -E -n -e 's/^[0-9a-z\.\_]+\=(.+)$/\1/p')
            sed -i -E -e "s#^\;?\s*${param}\s*\=\s*([^\n]+|$)#${param} = ${valor}#" ${file}
        done
    fi
}

remove_xdebug_ini() {
    if [ -f ${cli_confdir}/conf.d/20-xdebug.ini ]; then
        rm -f ${cli_confdir}/conf.d/20-xdebug.ini
    fi
    if [ -f ${sapi_confdir}/conf.d/20-xdebug.ini ]; then
        rm -f ${sapi_confdir}/conf.d/20-xdebug.ini
    fi
}

remove_opcache_ini() {
    if [ -f ${cli_confdir}/conf.d/10-opcache.ini ]; then
        rm -f ${cli_confdir}/conf.d/10-opcache.ini
    fi
    if [ -f ${sapi_confdir}/conf.d/10-opcache.ini ]; then
        rm -f ${sapi_confdir}/conf.d/10-opcache.ini
    fi
}

size_unit="k"
time_unit="s"

file_descriptors=$(ulimit -n) # worker_connections
qtd_cpus=$(sed -n '/processor/p' /proc/cpuinfo | wc -l) # worker_processes
mempage=$(getconf PAGESIZE)
mempage_size=$((${mempage} / 1024)) # B => k

# PHP.ini
max_execution_time=$((30*8)) # Facilitar debug
output_buffering=${mempage} # mempage_size in Bytes
max_input_vars=4000
memory_limit=128 # Megabytes

# Libera captura de variáveis de ambiente
sed -E -i -e 's/^\;clear_env/clear_env/' ${pool_conf}

DEFAULT_PHP_INI=''
if [ "${APP_ENV}" = "prod" ]; then
    max_execution_time=10 # impede scripts bosta
    memory_limit=$((${memory_limit} * 10 / 100)) # 10%. Impede scripts bosta

    DEFAULT_PHP_INI="cgi.fix_pathinfo=0 display_startup_errors=Off memory_limit=${memory_limit}M zend.assertions=-1 report_memleaks=Off display_errors=Off log_errors=Off expose_php=Off max_execution_time=${max_execution_time} date.time_zone=America/Manaus session.cookie_secure=On"
fi
if [ "${APP_ENV}" = "dev" ]; then
    DEFAULT_PHP_INI="cgi.fix_pathinfo=0 display_startup_errors=On implicit_flush=On memory_limit=${memory_limit}M display_errors=On log_errors=On expose_php=On max_execution_time=${max_execution_time} date.time_zone=America/Manaus session.cookie_secure=Off"
fi

# Maximum time in seconds a script is allowed to parse input data, like POST and GET.
# Timing begins at the moment PHP is invoked at the server and ends when execution begins.
max_input_time=$((${max_execution_time} * 10 / 100)) # 10%

if [ -n "${PHP_INI_CONF}" ];then
    # Concatena
    PHP_INI_CONF="${DEFAULT_PHP_INI} ${PHP_INI_CONF}"
else
    PHP_INI_CONF=${PHP_INI_CONF:-${DEFAULT_PHP_INI}}
fi

if [ -n "${PHP_INI_CONF}" ];then
    update_config "${sapi_confdir}/fpm/php.ini" "${PHP_INI_CONF}"
    update_config ${cli_confdir}/${cli_ini} "${PHP_INI_CONF}"
fi

# control opcache lib load
if [[ ( -f ${extension_dir}/opcache.so ) && ( "${APP_ENV}" = "debug"  || "${APP_ENV}" = "prod" ) ]]; then
    qtd_php_files=65406
    if [ -d /var/www/html ];then
        qtd_php_files=$(find /var/www/html -name "*.php" | wc -l)
    fi
    max_accelerated_files=$(( ${qtd_php_files} / 100 + ${qtd_php_files} ))
    DEFAULT="enable=1 enable_cli=0 memory_consumption=256 interned_strings_buffer=16 validate_timestamps=0 revalidate_freq=0 enable_file_override=1 save_comments=0 error_log='/var/log/php-opcache-error.log' max_accelerated_files=${max_accelerated_files} fast_shutdown=1"
    OPCACHE_CONF=${OPCACHE_CONF:-${DEFAULT}}
    if [ "${OPCACHE_CONF}" = "off" ]; then
        remove_opcache_ini
    else
        ENABLE_JIT=${ENABLE_JIT:-1}
        if [  ${ENABLE_JIT} -eq 1 ]; then
            # reference: https://www.stitcher.io/blog/php-8-jit-setup
            OPCACHE_CONF="${OPCACHE_CONF} opcache.jit=1255 opcache.jit_buffer_size=200M"
        fi
        if [ ! -f "${sapi_confdir}/conf.d/10-opcache.ini" ];then
            echo "[opcache]" > ${sapi_confdir}/conf.d/10-opcache.ini
            echo "zend_extension=${extension_dir}/opcache.so" >> ${sapi_confdir}/conf.d/10-opcache.ini
        fi
        opcache_confs=($(echo ${OPCACHE_CONF}))
        for conf in "${opcache_confs[@]}"; do
            echo "opcache.${conf}" >> ${sapi_confdir}/conf.d/10-opcache.ini
        done

    fi
fi

if [[ ( -f ${extension_dir}/xdebug.so ) && ( "${APP_ENV}" = "debug"  || "${APP_ENV}" = "dev" ) ]]; then
    hospedeiro=$(/sbin/ip route|awk '/default/ { print $3 }')
    if [ ${ENABLE_FPM_SOCKET} -ne 1 ];then
        xdebug_default_port=9003
    fi
    DEFAULT="mode=develop,debug start_with_request=yes client_port=${xdebug_default_port} idekey=VSCODE client_host=${hospedeiro}"
    XDEBUG_CONFIG=${XDEBUG_CONFIG:-${DEFAULT}}
    if [ "${XDEBUG_CONFIG}" = "off" ]; then
        remove_xdebug_ini
    else
        if [ ! -f "${sapi_confdir}/conf.d/20-xdebug.ini" ]; then
            echo "[Xdebug]" > "${sapi_confdir}/conf.d/20-xdebug.ini"
            echo "zend_extension=${extension_dir}/xdebug.so" >> ${sapi_confdir}/conf.d/20-xdebug.ini
        fi
        confs=($(echo ${XDEBUG_CONFIG}))
        for conf in "${confs[@]}"; do
            echo "xdebug.${conf}" >> ${sapi_confdir}/conf.d/20-xdebug.ini
        done
    fi
fi

# control parallel lib load
if [ -f ${extension_dir}/parallel.so ]; then
    ENABLE_PARALLEL=${ENABLE_PARALLEL:-"on"}
    if [ ${ENABLE_PARALLEL} = "on" ]; then
        echo "[parallel]" > ${sapi_confdir}/conf.d/20-parallel.ini
        echo "extension=${extension_dir}/parallel.so" > ${sapi_confdir}/conf.d/20-parallel.ini
    fi
fi

if [ -f ${extension_dir}/swoole.so ]; then
    ENABLE_SWOOLE=${ENABLE_SWOOLE:-"off"}
    if [ ${ENABLE_SWOOLE} = "off" ]; then
        rm -fr ${sapi_confdir}/conf.d/20-swoole.ini
    fi
fi
if [ -f ${extension_dir}/amqp.so ]; then
    ENABLE_AMQP=${ENABLE_AMQP:-"off"}
    if [ ${ENABLE_AMQP} = "off" ]; then
        rm -fr ${sapi_confdir}/conf.d/20-amqp.ini
    fi
fi
if [ -f ${extension_dir}/sodium.so ]; then
    ENABLE_SODIUM=${ENABLE_SODIUM:-"on"}
    if [ ${ENABLE_SODIUM} = "on" ]; then
        rm -fr ${sapi_confdir}/conf.d/20-sodium.ini
    fi
fi
if [ -f ${extension_dir}/decimal.so ]; then
    ENABLE_DECIMAL=${ENABLE_DECIMAL:-"on"}
    if [ ${ENABLE_DECIMAL} = "on" ]; then
        rm -fr ${sapi_confdir}/conf.d/20-decimal.ini
    fi
fi

if [ -f ${extension_dir}/redis.so ]; then
    REDIS_CONF=${REDIS_CONF:-"off"}
    if [ "${REDIS_CONF}" = "off" ]; then
        if [ -f "${sapi_confdir}/conf.d/20-redis.ini" ]; then
            rm -f ${sapi_confdir}/conf.d/20-redis.ini
        fi
    else
        REDIS_CONF="session.probability=0 ${REDIS_CONF}"
        if [ ! -f "${sapi_confdir}/conf.d/20-redis.ini" ]; then
            echo "[redis]" > ${sapi_confdir}/conf.d/20-redis.ini
            echo "extension=${extension_dir}/redis.so" > ${sapi_confdir}/conf.d/20-redis.ini
        fi
        update_config "${sapi_confdir}/fpm/php.ini" "${REDIS_CONF}"
    fi
fi

if [ -f ${extension_dir}/swoole.so ]; then
    ENABLE_SWOOLE=${ENABLE_SWOOLE:-0}
    if [ ${ENABLE_SWOOLE} -eq 1 ]; then
        echo "[swoole]" > ${config_dir}/20-swoole.ini
        echo "extension=${extension_dir}/swoole.so" >> ${config_dir}/20-swoole.ini
    fi
fi

if [ -f ${extension_dir}/memcached.so ]; then 
    ENABLE_MEMCACHED=${ENABLE_MEMCACHED:-"off"}
    if [ ${ENABLE_MEMCACHED} = "on" ]; then
        echo "[memcached]" > ${sapi_confdir}/conf.d/20-memcached.ini
        echo "extension=${extension_dir}/memcached.so" > ${sapi_confdir}/conf.d/20-memcached.ini
    fi
fi

if [ -f ${extension_dir}/mongodb.so ]; then
    ENABLE_MONGODB=${ENABLE_MONGODB:-"off"}
    if [ ${ENABLE_MONGODB} = "on" ]; then
        echo "[mongodb]" > ${sapi_confdir}/conf.d/20-mongodb.ini
        echo "extension=${extension_dir}/mongodb.so" > ${sapi_confdir}/conf.d/20-mongodb.ini
    fi
fi

# configure supervisor
sed -i -E -e "s|command=|command=/usr/sbin/php-fpm --fpm-config /etc/php/${php_version}/fpm/php-fpm.conf --pid /run/php/php-fpm.pid -F|g" /etc/supervisor/conf.d/supervisord.conf

if [ ${ENABLE_FPM_SOCKET} = "on" ];then
    sed -i -E -e "s|listen = 127\.0\.0\.1\:9000|listen = /run/php/php${major}-fpm.sock|g" ${pool_conf}
else
    sed -i -E -e "s|listen = /run/php/php${major}-fpm.sock|listen = 127\.0\.0\.1\:9000|g" ${pool_conf}
fi


WEB_SERVER=${WEB_SERVER:-"on"}
if [ "${WEB_SERVER}" = "on" ] && [ -f /run/init/webserver ]; then
    /run/init/webserver ${APP_ENV} ${max_execution_time} ${max_input_time} ${output_buffering} ${mempage} ${mempage_size} ${qtd_cpus} ${file_descriptors} ${major} ${SERVER_NAME}
fi

# Força finalização processamento, caso max_execution_time falhe
sed -E -i -e '/^listen.group \=/a\' -e "request_terminate_timeout = $((${max_execution_time} * 10 / 100 + ${max_execution_time}))" ${pool_conf}

RAW_POOL=${RAW_POOL:-''}
if [ -n "${RAW_POOL}" ]; then
    update_config "${pool_conf}" "${RAW_POOL}"
fi

if [ "${APP_ENV}" = "prod" ];then
    # Define PM com static
    sed -E -i -e 's/pm = dynamic/pm = static/;s/pm.max_children = [0-9]+/pm.max_children = 10/;/pm.start_servers/d;/pm.min_spare_servers/d;/pm.max_spare_servers/d' ${pool_conf}
    sed -E -i -e '/pm.max_children/a\' -e 'pm.max_requests = 500' ${pool_conf}

    # Remove comentários
    sed -i -E '/(^;|^$)/d' ${sapi_confdir}/fpm/php.ini
    sed -i -E '/(^;|^$)/d' ${cli_confdir}/${cli_ini}
    sed -i -E '/(^;|^$)/d' ${pool_conf}
fi

# Configure supervisor
sed -E -i -e '/pidfile/a user=root \;' /etc/supervisor/supervisord.conf

if [ ! -d /var/log/supervisor ];then
    mkdir -p /var/log/supervisor
fi

/run/init/hook-start

echo -e "Configurations:
    Infrastructure values:

        file_descriptors=${file_descriptors} # worker_connections
        qtd_cpus=${qtd_cpus} # worker_processes
        mempage=${mempage} B
        mempage_size=${mempage_size} # KB 

        # PHP.ini
        max_execution_time=${max_execution_time} # seconds
        output_buffering=${mempage} # B
        max_input_vars=${max_input_vars}
        memory_limit=${memory_limit} # Mb

    Environment variables:

        APP_ENV             = ( dev* | prod* | debug )

            Current: '${APP_ENV}'
        
        WEB_SERVER          = ( on | off )

            * Enable nginx webserver

            Current: '${WEB_SERVER}' 

        ENABLE_FPM_SOCKET   = ( on | off ) 

            * Enable PHP connections through PHP-FPM socket file

            Current: '${ENABLE_FPM_SOCKET}'

        DEFAULT_PHP_INI     = ( dev | prod | personal )

            * PHP configurations in $(php-config --ini-path)/php.ini

            dev:
                cgi.fix_pathinfo=0 display_startup_errors=On implicit_flush=On memory_limit=${memory_limit}M display_errors=On log_errors=On expose_php=On max_execution_time=${max_execution_time} date.time_zone=America/Manaus session.cookie_secure=Off
            prod:
                cgi.fix_pathinfo=0 display_startup_errors=Off memory_limit=${memory_limit}M zend.assertions=-1 report_memleaks=Off display_errors=Off log_errors=Off expose_php=Off max_execution_time=${max_execution_time} date.time_zone=America/Manaus session.cookie_secure=On
            personal: 
                Your personal PHP configurations

            Current: '${DEFAULT_PHP_INI}'

        OPCACHE_CONF = ( \$config | off )
    
            * Configure opcache or disable it
            * When APP_ENV='dev', OPCACHE_CONF=off by default

            \$config=\"enable=1 enable_cli=0 memory_consumption=256 interned_strings_buffer=16 validate_timestamps=0 revalidate_freq=0 enable_file_override=1 save_comments=0 error_log='/var/log/php-opcache-error.log' max_accelerated_files=${max_accelerated_files} fast_shutdown=1\"

            Current: '${OPCACHE_CONF}'

        XDEBUG_CONFIG = ( \$config | off )

            * Configure xdebug or disable it
            * When APP_ENV=prod, XDEBUG_CONFIG=off

            \$config=\"mode=develop,debug start_with_request=yes client_port=${xdebug_default_port} idekey=VSCODE client_host=${hospedeiro}\"
    
            Current: '${XDEBUG_CONFIG}'

        RAW_POOL     = ( \$config | '' )

            * Like php.ini conf, RAW_POOL must be used to configure main php-fpm pool

"

# start supervisor and send to background
/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
